Deploy Phase: DB Migration, Deploy Frontend, backend; Smoke Test, Rollback

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,22 +19,27 @@ commands:
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
-    #parameters:
-      # Add parameter here     
+    parameters:
+      # Add parameter here   
+      workflowid:
+        type : string      
     steps:
       - run:
           name: Revert migrations
           # Add when this will run
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
+            # Your Memstash or kvdb.io GET URL code goes here
+            # Example: Memstash.io
+            # SUCCESS=$(curl -H "token: e52b52de-ee26-41a5-86e8-e8dcc3d995a5" --request GET https://api.memstash.io/values/migration_<< parameters.workflow_id >>)
+            # Example: kvdb.io
+            SUCCESS=$(curl --insecure  https://kvdb.io/6XZPMXwv4UrWgTzrhNq4qq/migration_<< parameters.workflow_id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
-            fi
+                cd ~/project/backend
+                npm install
+                npm run migration:revert
+            fi  
             
 jobs:
   build-frontend:
@@ -234,84 +239,230 @@ jobs:
             "${CIRCLE_WORKFLOW_ID:0:7}" 
     
 
-#run-migrations:
-#  docker:
-#    # Docker image here that supports NodeJS
-#  steps:
-#    # Checkout code from git
-#    - run:
-#        name: Run migrations
-#        command: |
-#          # Your code here
-#          exit 1
-#    - run:
-#        name: Send migration results to memstash
-#        command: |
-#          # Your code here
-#          exit 1
-#   # Here's where you will add some code to rollback on failure      
-#
-#eploy-frontend:
-#  docker:
-#    # Docker image here that supports AWS CLI
-#  steps:
-#    # Checkout code from git
-#    - run:
-#        name: Install dependencies
-#        command: |
-#          # your code here
-#    - run:
-#        name: Get backend url
-#        command: |
-#          # your code here
-#          export API_URL="http://${BACKEND_IP}:3030"
-#          echo "${API_URL}"
-#    - run:
-#        name: Deploy frontend objects
-#        command: |
-#          # your code here
-#    # Here's where you will add some code to rollback on failure      
-#                 
-#eploy-backend:
-#  docker:
-#    # Docker image here that supports Ansible
-#  steps:
-#    # Checkout code from git
-#    # Add ssh keys with fingerprint
-#    # attach workspace
-#    - run:
-#        name: Install dependencies
-#        command: |
-#          # your code here
-#    - run:
-#        name: Deploy backend
-#        command: |
-#          # your code here
-#    # Here's where you will add some code to rollback on failure  
-#
-#moke-test:
-#  docker:
-#    # Lightweight Docker image 
-#  steps:
-#    # Checkout code from git
-#    - run:
-#        name: Install dependencies
-#        command: |
-#          # your code here
-#    - run:
-#        name: Get backend url
-#        command: |
-#          # your code here
-#    - run:
-#        name: Backend smoke test.
-#        command: |
-#          # your code here
-#    - run:
-#        name: Frontend smoke test.
-#        command: |
-#          # your code here
-#    # Here's where you will add some code to rollback on failure  
-#
+  run-migrations:
+    docker:
+         # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+
+    steps:
+    # Checkout code from git
+    - checkout
+      - restore_cache:
+          keys: [backend-build]
+
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            # Run and save the migration output
+            npm run migrations > migrations_dump.txt
+            # exit 1
+
+      - run:
+          name: Send migration status to kvdb.io OR memstash.io
+          command: |   
+              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                  # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+                  # curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+                  # If you are using kvdb.io, generate the bucket ID "6XZPMXwv4UrWgTzrhNq4qq" in your local terminal first
+                  curl https://kvdb.io/6XZPMXwv4UrWgTzrhNq4qq/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              fi
+            # exit 1
+    # Here's where you will add some code to rollback on failure   
+     - destroy-environment:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}"   
+     - revert-migrations:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}" 
+
+
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: python:3.10-alpine3.16
+    steps:
+      # Checkout code from git
+      - checkout
+
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update ansible 
+            apk add --update tar gzip curl
+            apk add --update openssh-client git
+            apk add --update nodejs
+            apk add --update npm
+            apk add --update --no-cache aws-cli
+
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:project,Values=udapeople" \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            # your code here
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+
+            echo "URL : http://${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+      # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}"    
+      - revert-migrations:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}" 
+
+
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.10-alpine3.16
+
+    steps:
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint
+        - add_ssh_keys: 
+          fingerprints: ["66:d2:5e:0a:2a:c6:af:b0:43:ad:02:e2:de:8b:68:5c"]
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update ansible 
+            apk add --update tar gzip curl
+            apk add --update openssh-client git
+            apk add --update nodejs
+            apk add --update npm
+            apk add --update --no-cache aws-cli
+
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            mkdir ~/project/.circleci/ansible/roles/deploy/files
+            cp artifact.tar.gz ~/project/.circleci/ansible/roles/deploy/files/
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+
+      - persist_to_workspace:
+          root: ~/
+          paths: 
+            - project/artifact.tar.gz
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}"    
+      - revert-migrations:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}" 
+
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: python:3.10-alpine3.16
+
+    steps:
+      # Checkout code from git
+      - checkout
+
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update tar gzip curl
+            apk add --update openssh-client git
+            apk add --update nodejs
+            apk add --update npm
+            apk add --update --no-cache aws-cli
+
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+              # Fetch and prepare the BACKEND_IP env var
+              BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople" \
+              --output text)
+              echo "$BACKEND_IP"
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:project,Values=udapeople" \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
+
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}"    
+      - revert-migrations:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}" 
+
+  
 #loudfront-update:
 #  docker:
 #    # Docker image here that supports AWS CLI
@@ -367,14 +518,14 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      #- run-migrations:
-      #    requires: [configure-infrastructure]
-      #- deploy-frontend:
-      #    requires: [run-migrations]
-      #- deploy-backend:
-      #    requires: [run-migrations]
-      #- smoke-test:
-      #    requires: [deploy-backend, deploy-frontend]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       #- cloudfront-update:
       #    requires: [smoke-test]
       #- cleanup:
